name: CI
on:
  push:
    branches: [ master ]

jobs:
  build-aarch64:
    # The host should always be Linux
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    name: Build on aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Use cachix
        uses: cachix/cachix-action@v12
        with:
          name: stripeapi
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: build
        run: nix build .#stripeapi -Lv

  build-x86-64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Use cachix
        uses: cachix/cachix-action@v12
        with:
          name: stripeapi
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: build
        run: nix build .#stripeapi -Lv
